Repository 42-Gang/fastify-boilerplate, pull requests merged in 2025-03, with the labels that each got.

#1 [FEAT] main.ts 리펙토링 및 app.ts 추가
  @types/global.d.ts
  package.json
  src/app.ts
  src/main.ts
Labels: ✨ Feature, 🔨 Refactor

#6 Feature/2 로그인 관련 api 작성
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature.md
  .prettierrc
  @types/global.d.ts
  eslint.config.mjs
  package.json
  src/app.ts
  src/main.ts
  src/v1/constants/status.ts
  src/v1/controllers/auth.controller.ts
  src/v1/controllers/users.controller.ts
  src/v1/index.ts
  src/v1/routes/auth.route.ts
  src/v1/routes/users.route.ts
  src/v1/schemas/auth.schema.ts
  src/v1/schemas/core.schema.ts
  src/v1/services/auth.service.ts
  tsconfig.json
Labels: ⚙ Setting, ✨ Feature, 📬 API

#8 Feature/3 boilerplate에 prisma - mariadb 설정 추가
  .gitignore
  prisma/schema.prisma
Labels: ⚙ Setting

#11 [FEAT] 4 prisma mariadb api 테스트
  .env.example
  package.json
  prisma/schema.prisma
  src/v1/services/auth.service.ts
  src/v1/utils/prisma.ts
Labels: ✨ Feature, 📬 API

#15 [FEAT] 9 jwt관련 설정 및 구현
  .gitignore
  eslint.config.mjs
  jest.config.js
  package.json
  prisma/schema.prisma
  src/app.ts
  src/main.ts
  src/v1/controllers/auth.controller.ts
  src/v1/controllers/users.controller.ts
  src/v1/plugins/jwt-plugin.ts
  src/v1/routes/auth.route.ts
  src/v1/routes/users.route.ts
  src/v1/schemas/core.schema.ts
  src/v1/schemas/user.schema.ts
  src/v1/services/auth.service.ts
  src/v1/types/fastify.d.ts
  src/v1/types/global.d.ts
  src/v1/utils/prisma.ts
  src/v1/utils/router.ts
  test/v1/mocks/mockJwt.ts
  test/v1/mocks/mockLogger.ts
  test/v1/mocks/mockPrisma.ts
  test/v1/services/auth.service.spec.ts
  test/vitest.setup.ts
  tsconfig.eslint.json
  tsconfig.json
  vitest.config.ts
Labels: ✨ Feature

#18 [FEAT] 7 swagger 추가
  .gitignore
  eslint.config.mjs
  package.json
  src/main.ts
  src/v1/constants/swagger_config.ts
  src/v1/routes/auth.route.ts
  src/v1/utils/swagger-plugin.ts
  tsconfig.json
Labels: ⚙ Setting, 📃 Docs

#19 [REFAC] 16 파일 구조 변경
  package.json
  src/app.ts
  src/main.ts
  src/v1/apis/auth/auth.controller.ts
  src/v1/apis/auth/auth.route.ts
  src/v1/apis/auth/auth.schema.ts
  src/v1/apis/auth/auth.service.ts
  src/v1/apis/users/user.schema.ts
  src/v1/apis/users/users.controller.ts
  src/v1/apis/users/users.route.ts
  src/v1/common/constants/status.ts
  src/v1/common/constants/swagger_config.ts
  src/v1/common/exceptions/core.error.ts
  src/v1/common/plugins/jwt-plugin.ts
  src/v1/common/schema/core.schema.ts
  src/v1/common/types/fastify.d.ts
  src/v1/common/types/global.d.ts
  src/v1/common/utils/prisma.ts
  src/v1/common/utils/router.ts
  src/v1/common/utils/swagger-plugin.ts
  src/v1/index.ts
  test/v1/apis/auth/services/auth.service.spec.ts
  test/v1/mocks/mockPrisma.ts
Labels: 🔨 Refactor

#20 [REFACTOR] 17 di적용 및 dip준수
  @types/global.d.ts
  eslint.config.mjs
  package.json
  src/app.ts
  src/main.ts
  src/v1/apis/auth/auth.controller.ts
  src/v1/apis/auth/auth.route.ts
  src/v1/apis/auth/auth.service.ts
  src/v1/apis/users/users.controller.ts
  src/v1/apis/users/users.route.ts
  src/v1/repositories/base.repository.ts
  src/v1/repositories/user.repository.ts
  test/v1/apis/auth/services/auth.service.spec.ts
  test/vitest.setup.ts
  tsconfig.json
Labels: ⚙ Setting, ✨ Feature

#23 [FEAT]12 redis kafka 연결
  @types/global.d.ts
  package.json
  src/app.ts
  src/container.ts
  src/main.ts
  src/v1/apis/auth/auth.controller.ts
  src/v1/apis/auth/auth.service.ts
  src/v1/apis/users/users.controller.ts
  src/v1/apis/users/users.schema.ts
  src/v1/apis/users/users.service.ts
  src/v1/common/schema/core.schema.ts
  src/v1/storage/cache/interfaces/base.cache.interface.ts
  src/v1/storage/cache/interfaces/user.cache.interface.ts
  src/v1/storage/cache/redis/user.cache.repository.ts
  src/v1/storage/database/interfaces/base.repository.interface.ts
  src/v1/storage/database/interfaces/user.repository.interface.ts
  src/v1/storage/database/prisma/user.repository.ts
  test/v1/apis/auth/services/auth.service.spec.ts
Labels: ⚙ Setting, ✨ Feature

#24 [FEAT] 22 소켓통신 테스트 socketio
  package.json
  src/main.ts
  src/socket.ts
  src/v1/sockets/chat/chat.namespace.ts
  src/v1/sockets/chat/chat.schema.ts
  src/v1/sockets/gateway.ts
Labels: ⚙ Setting, ✨ Feature

#25 [FEAT] 14 서버간 통신 인터페이스 구성
  package.json
  src/container.ts
  src/v1/apis/auth/auth.service.ts
  src/v1/common/http/got/http.client.ts
  src/v1/common/http/interface/http.client.interface.ts
  test/v1/common/http/got/http.client.spec.ts
Labels: ⚙ Setting, ✅ Test

#26 [FEAT] 21 refactor 마지막 리펙토링
  .env.example
  @types/global.d.ts
  package.json
  prisma/schema.prisma
  src/app.ts
  src/container.ts
  src/main.ts
  src/plugins/container.ts
  src/plugins/http/got/http.client.ts
  src/plugins/http/interface/http.client.interface.ts
  src/plugins/jwt-plugin.ts
  src/plugins/prisma.ts
  src/plugins/router.ts
  src/plugins/socket.ts
  src/plugins/swagger/swagger-config.ts
  src/plugins/swagger/swagger-plugin.ts
  src/server-config.ts
  src/server-utils.ts
  src/v1/apis/auth/auth.route.ts
  src/v1/apis/users/users.route.ts
  src/v1/common/http/interface/http.client.interface.ts
  src/v1/common/utils/prisma.ts
  test/plugins/http/got/http.client.spec.ts
  test/v1/common/http/got/http.client.spec.ts
  test/v1/mocks/mockPrisma.ts
Labels: 🔨 Refactor
